### ISSUE TITLE
Source of data

### ISSUE THREAD

**Issue by Arjun9088** [amith-vp/Kerala-Private-Bus-Timing#5]
~~Hi, thanks for creating this repo. I wanted to use this data, however for that, I wanted to know the source of the data. I couldn't find any mention of the source other than "**This dataset is compiled from publicly available information and may not encompass the complete Kerala private bus schedule or accurate data**". Is it possible to provide details on how these PDF's were sourced(RTI?)~~

Should have read the readme properly, the source is RTI. Closing this issue

**Comment by amith-vp** [comment]
@Arjun9088 

This data was published by the Motor Vehicle Department on their own website. Later, they removed it from the website listing, although the files are still accessible

https://mvd.kerala.gov.in/sites/default/files/2023-03/RMS%20kannur.pdf
https://mvd.kerala.gov.in/sites/default/files/2023-02/RMS%20DATA.%2C.pdf 
https://mvd.kerala.gov.in/sites/default/files/2023-01/RMS%20KOTTAYAM_compressed.pdf 
https://mvd.kerala.gov.in/sites/default/files/2023-01/RMS%20Palakkad1.pdf 
https://mvd.kerala.gov.in/sites/default/files/2023-01/RMS%20Palakkad2.pdf 
https://mvd.kerala.gov.in/sites/default/files/2022-12/RMS%20-%20MVPA%20-%20Publication_0.pdf 
https://mvd.kerala.gov.in/sites/default/files/2022-12/RMS%20-%20MVPA%20-%20Publication.pdf 
https://mvd.kerala.gov.in/sites/default/files/2022-11/RMS%20Time%20Sheet%20RTO%20KOZHIKODE.pdf 
https://mvd.kerala.gov.in/sites/default/files/2022-11/RMS%20Time%20Sheet%20RTO%20Idukki.pdf 
https://mvd.kerala.gov.in/sites/default/files/2022-11/RMS%20time%20sheet%20RTO%20Vadakara.pdf 
https://mvd.kerala.gov.in/sites/default/files/2022-11/RMS%20-%20KL12%20WAYANAD%20-%20APPROVED%20SC%20PERMIT%20TIME%20SHEET_compressed.pdf
https://mvd.kerala.gov.in/sites/default/files/2022-11/route%20management%20report-kl14.pdf 
https://mvd.kerala.gov.in/sites/default/files/2022-11/RMS-EKM-to%20upload.pdf 
https://mvd.kerala.gov.in/sites/default/files/2022-11/Tvpm_compressed%201.pdf 
https://mvd.kerala.gov.in/sites/default/files/2023-01/Tvpm_compressed%202.pdf 
https://mvd.kerala.gov.in/sites/default/files/2022-11/RMS%20RTO%20Alappuzha-1.pdf 
https://mvd.kerala.gov.in/sites/default/files/2022-11/Time%20sheets%20Pathanamthitta%20consolidated%20pdf.pdf 
https://mvd.kerala.gov.in/sites/default/files/2022-11/rms%20kollam.pdf 
https://mvd.kerala.gov.in/sites/default/files/2022-11/RMS%20attingal%20FINAL.pdf
